[workspace]
members = [ "src/services/sealingService/sealingService" ]

[workspace.dependencies.curl-effector-imports]
version = "0.1.2"

[workspace.dependencies.ipfs-effector-imports]
version = "0.1.1"
